"""Initial schema with users, channels, messages, summaries

Revision ID: be3f078b6cf1
Revises: 
Create Date: 2026-01-16 11:44:31.539651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'be3f078b6cf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('channels', sa.Column('detected_language', sa.String(length=10), nullable=True))
    op.add_column('channels', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('fetch_config', sa.JSON(), nullable=True))
    op.add_column('channels', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('channels', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('channels', 'telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('channels', 'subscriber_count',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.create_index('ix_channels_active_username', 'channels', ['is_active', 'username'], unique=False)
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.drop_column('channels', 'language')
    op.add_column('messages', sa.Column('target_language', sa.String(length=10), nullable=True))
    op.add_column('messages', sa.Column('originality_score', sa.SmallInteger(), nullable=True))
    op.add_column('messages', sa.Column('embedding_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'channel_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('messages', 'media_urls',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('messages', 'duplicate_group_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index('ix_messages_channel_published', 'messages', ['channel_id', 'published_at'], unique=False)
    op.create_index('ix_messages_channel_telegram_id', 'messages', ['channel_id', 'telegram_message_id'], unique=True)
    op.create_index('ix_messages_duplicate_group', 'messages', ['duplicate_group_id'], unique=False, postgresql_where=sa.text('duplicate_group_id IS NOT NULL'))
    op.create_index(op.f('ix_messages_is_duplicate'), 'messages', ['is_duplicate'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.add_column('summaries', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('summaries', sa.Column('digest_type', sa.String(length=50), nullable=True))
    op.add_column('summaries', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('summaries', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('channels_covered', sa.Integer(), nullable=True))
    op.add_column('summaries', sa.Column('duplicates_filtered', sa.Integer(), nullable=True))
    op.add_column('summaries', sa.Column('filters', sa.JSON(), nullable=True))
    op.alter_column('summaries', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('summaries', 'period_start',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('summaries', 'period_end',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_summary_type'), table_name='summaries')
    op.create_index(op.f('ix_summaries_digest_type'), 'summaries', ['digest_type'], unique=False)
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.create_index('ix_summaries_user_type_date', 'summaries', ['user_id', 'digest_type', 'generated_at'], unique=False)
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('summaries', 'summary_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('summary_type', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.drop_index('ix_summaries_user_type_date', table_name='summaries')
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_digest_type'), table_name='summaries')
    op.create_index(op.f('ix_summaries_summary_type'), 'summaries', ['summary_type'], unique=False)
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.alter_column('summaries', 'period_end',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('summaries', 'period_start',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('summaries', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('summaries', 'filters')
    op.drop_column('summaries', 'duplicates_filtered')
    op.drop_column('summaries', 'channels_covered')
    op.drop_column('summaries', 'content_html')
    op.drop_column('summaries', 'title')
    op.drop_column('summaries', 'digest_type')
    op.drop_column('summaries', 'user_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'])
    op.drop_index(op.f('ix_messages_is_duplicate'), table_name='messages')
    op.drop_index('ix_messages_duplicate_group', table_name='messages', postgresql_where=sa.text('duplicate_group_id IS NOT NULL'))
    op.drop_index('ix_messages_channel_telegram_id', table_name='messages')
    op.drop_index('ix_messages_channel_published', table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('messages', 'duplicate_group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('messages', 'media_urls',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'telegram_message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'channel_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'translated_at')
    op.drop_column('messages', 'entities')
    op.drop_column('messages', 'embedding_id')
    op.drop_column('messages', 'originality_score')
    op.drop_column('messages', 'target_language')
    op.add_column('channels', sa.Column('language', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.drop_index('ix_channels_active_username', table_name='channels')
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.alter_column('channels', 'subscriber_count',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('channels', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('channels', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('channels', 'updated_at')
    op.drop_column('channels', 'fetch_config')
    op.drop_column('channels', 'is_active')
    op.drop_column('channels', 'detected_language')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
